version: "2"
volumes:
  mongo-data:
services:
  proxy:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes_from:
      - proxy-conf
      - provt
    links:
      - provt-server
  proxy-conf:
    build: ./provt-proxy-conf
    image: samoyeds/provt-nginx-conf:0.1.1
    entrypoint: /bin/true
    volumes:
      - /etc/nginx/conf.d
  provt:
    build: ./provt-ui
    image: samoyeds/provt:0.1.1
    entrypoint: /bin/true
    volumes:
      - /app/dist

  provt-server:
    build: ./provt-server
    image: samoyeds/provt-server:0.1.1
    environment:
      - MONGO_URI=mongodb://mongo/provt
    links:
      - mongo

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
